--
-- Copyright (c) 2009 Meding Software Technik - All Rights Reserved
--
-- Defines the date dimension
--

--
-- @{
-- types     = $sysmodelpath/DatatypeSQL.map
-- decls     = $sysmodelpath/NetworkStatus.map
-- mapping   = build/models/NETWORK_STATUS_SQL_MAPPING
-- @}
--

-- @wurblet $mapping IncludeMappings $types $decls -line-comment=--

-- <editor-fold defaultstate="collapsed" desc="Code generated by wurblet. Do not edit!">//{{{build/models/NETWORK_STATUS_SQL_MAPPING

--
-- @> build/models/NETWORK_STATUS_SQL_MAPPING
-- # ======>>>> /home/uwe/project/SW/tentackle-php/example/models/DatatypeSQL.map
-- 
-- # { mysql(boolean) type(TINYINT) }
-- # { mysql(byte) type(TINYINT) }
-- # { mysql(char) type(CHAR) }
-- # { mysql(character) type(CHAR) }
-- # { mysql(short) type(SMALLINT) }
-- # { mysql(int) type(INT) }
-- # { mysql(long) type(BIGINT) }
-- # { mysql(float) type(FLOAT) }
-- # { mysql(double) type(DOUBLE) }
-- # { mysql(date) type(DATE) }
-- # { mysql(time) type(DATETIME) }
-- # { mysql(timestamp) type(DATETIME) }
-- 
-- # { mysql(String) type(VARCHAR) }
-- # { mysql(binary) type(BLOB) }
-- 
-- 
-- # ======>>>> /home/uwe/project/SW/tentackle-php/example/models/NetworkStatus.map
-- Timestamp	0	when				ts				When we collected the details
-- 
-- String 		80	interfaceName		if_name			Network interface name
-- 
-- long		11	rxTotalBytes		rx_tot_bytes	Number of bytes
-- long		11	rxRelativeBytes		rx_rel_bytes	Number of bytes
-- long		11	rxPackets			rx_packets		Number of packets
-- long		11	rxErrors			rx_errs			Number of errors
-- long		11	rxDrop				rx_drop			Number dropped
-- 
-- long		11	txTotalBytes		tx_tot_bytes	Number of bytes
-- long		11	txRelativeBytes		tx_rel_bytes	Number of bytes
-- long		11	txPackets			tx_packets		Number of packets
-- long		11	txErrors			tx_errs			Number of errors
-- long		11	txDrop				tx_drop			Number dropped
-- 
-- String		10	bootProtocol		boot_as			Advertised boot protocol
-- 
-- String		20	hwAddr				hw_addr			Hardware address (MAC)
-- String 		20	ipAddr				ip_addr			IP address
-- String		20	gateway				gateway			Network gateway address
-- String		40	hostname			hostname		Host name
-- 
-- String		80	dnsSearchDomains	dns_search		DNS search domains
-- String		80	dnsNameServers		dns_nameservers	DNS name servers
-- 
-- @<
--

-- </editor-fold>//}}}build/models/NETWORK_STATUS_SQL_MAPPING


-- @wurblet network_statuses SQLCreateTable $mapping

-- <editor-fold defaultstate="collapsed" desc="Code generated by wurblet. Do not edit!">//{{{network_statuses

CREATE TABLE `network_statuses` (
                 id BIGINT(20)      NOT NULL, -- Record key
             serial BIGINT(20)      NOT NULL, -- Record serial
               `ts` Timestamp       NOT NULL, -- When we collected the details
          `if_name` VARCHAR(80)     NOT NULL, -- Network interface name
     `rx_tot_bytes` BIGINT(11)      NOT NULL, -- Number of bytes
     `rx_rel_bytes` BIGINT(11)      NOT NULL, -- Number of bytes
       `rx_packets` BIGINT(11)      NOT NULL, -- Number of packets
          `rx_errs` BIGINT(11)      NOT NULL, -- Number of errors
          `rx_drop` BIGINT(11)      NOT NULL, -- Number dropped
     `tx_tot_bytes` BIGINT(11)      NOT NULL, -- Number of bytes
     `tx_rel_bytes` BIGINT(11)      NOT NULL, -- Number of bytes
       `tx_packets` BIGINT(11)      NOT NULL, -- Number of packets
          `tx_errs` BIGINT(11)      NOT NULL, -- Number of errors
          `tx_drop` BIGINT(11)      NOT NULL, -- Number dropped
          `boot_as` VARCHAR(10)     NOT NULL, -- Advertised boot protocol
          `hw_addr` VARCHAR(20)     NOT NULL, -- Hardware address (MAC)
          `ip_addr` VARCHAR(20)     NOT NULL, -- IP address
          `gateway` VARCHAR(20)     NOT NULL, -- Network gateway address
         `hostname` VARCHAR(40)     NOT NULL, -- Host name
       `dns_search` VARCHAR(80)     NOT NULL, -- DNS search domains
    `dns_nameservers` VARCHAR(80)     NOT NULL, -- DNS name servers
    PRIMARY KEY (id));

-- </editor-fold>//}}}network_statuses


