<?php
// wurblet generated by Wurbiler, see http://www.wurblizer.org for more details.

require_once('AbstractWurblet.php');
require_once('AbstractFlex.php');

class PHPGetTablename extends AbstractFlex {
  public function run() {
    parent::run();

/* vim: set filetype=php :*//*<?php*/
    $ac = $this->getArgCount();
    if($ac != 1)
        throw new Exception("usage: wurblet <guard> PHPGetTablename TABLENAME");

    $tablename = WurbUtil::translateVars($this->getArg(0), $this->getContainer()->getProperties(PROPSPACE_WURBLET));

    fwrite($this->out,$this->source[0]); //  /** * Get the datab...
    fwrite($this->out,$tablename);
    fwrite($this->out,$this->source[1]); // "; } 
/*?>*/
  }
}
?>
