<?php
// wurblet generated by Wurbiler, see http://www.wurblizer.org for more details.

require_once('AbstractWurblet.php');
require_once('AbstractFlex.php');

class SQLCreateTable extends AbstractFlex {
  public function run() {
    parent::run();

/* vim: set filetype=php :*//*<?php*/
    $ac = $this->getArgCount();
    if($ac != 1)
        throw new Exception("usage: wurblet <guard> SQLCreateTable <modelname>");

    $modelFile = WurbUtil::translateVars($this->getArg(0), $this->getContainer()->getProperties(PROPSPACE_WURBLET));

    // fetch the model
    $model = $this->newGeneric4ColModelInstance($modelFile);
    
    if($this->haveParameter('fieldAccess')) {
        $fieldAccess = $this->getParameter('fieldAccess');
    } else {
        $fieldAccess = "private";
    }

    if($this->haveParameter('dialect')) {
        $dialect = $this->getParameter('dialect');
    } else {
        $dialect = "mysql";
    }

    $format = "%15s %-15s NOT NULL, -- %s";
    $id_type = $model->getMappedDataType('long', $dialect).'(20)';
    $id_line = sprintf($format, 'id', $id_type, 'Record key');
    $serial_type = $model->getMappedDataType('long', $dialect).'(20)';
    $serial_line = sprintf($format, 'serial', $serial_type, 'Record serial');
    fwrite($this->out,$this->source[0]); // CREATE TABLE `
    fwrite($this->out,$this->getGuardName());
    fwrite($this->out,$this->source[1]); // ` ( 
    fwrite($this->out,$id_line);
    fwrite($this->out,$this->source[2]); //  
    fwrite($this->out,$serial_line);
    fwrite($this->out,$this->source[3]); //  
    foreach($model->getAttributeList() as $attr) {
        if(!isset($attr['nomethod'])) {
            $type_name = $model->getMappedDataType($attr['type'], $dialect);
            $type_len = $attr['length'] == 0 ? '' : '('.$attr['length'].')';
            $type = "$type_name$type_len";
            $line = sprintf($format, '`'.$attr['dbname'].'`', $type, $attr['comment']);
            fwrite($this->out,$this->source[4]); //  
            fwrite($this->out,$line);
            fwrite($this->out,$this->source[5]); //  
        }
    }
    fwrite($this->out,$this->source[6]); //  PRIMARY KEY (id)); 
/*?>*/
  }
}
?>
